### ISSUE TITLE
Command line longer than the terminal (wrapping on two lines) makes <Enter> copy the line, thus filling up the terminal

### ISSUE THREAD

**Issue by Aster89** [codekitchen/pipeline#10]
(I'm so bad at choosing issue title; feel free to edit it.)

Using `urxvt`:

[![asciicast](https://asciinema.org/a/b4Ak6CdZnvuSanDIgiArelyUC.svg)](https://asciinema.org/a/b4Ak6CdZnvuSanDIgiArelyUC)

_Originally posted by @Aster89 in https://github.com/codekitchen/pipeline/issues/2#issuecomment-600240887_

**Comment by codekitchen** [comment]
I just noticed this behavior affects the terminal emulator that's built-in to VS Code, as well

**Comment by codekitchen** [comment]
I think I see, iTerm is the odd one out here. I mostly use iTerm2 so I never ran into this myself. It seems to "remember" when a line is wrapped, and if I tell it to "move the cursor left 9999 chars" it'll actually follow those line wraps back up. Other term emulators don't do this, so I'll have to modify the code to actually measure the width of the command prompt vs terminal width and move the cursor appropriately.

**Comment by Aster89** [comment]
Guess what? This thing is extremely tricky! Look at this: the line is repeated if I hit <kbd>Enter</kbd> when the cursor is on the first character of the second (or third, fourth, ...) wrapped line.

Myabe the offset to which you consider to be on another line is biased by 1?

[![asciicast](https://asciinema.org/a/YPJUOeAbPTftYy3R1PKy7m3pl.svg)](https://asciinema.org/a/YPJUOeAbPTftYy3R1PKy7m3pl)

**Comment by codekitchen** [comment]
Hm this is a case I specifically tested when making this change, because I was worried about it. I can't repro this in any of my environments. Are you using the latest master that includes this fix, or are you on pipeline v1.5 ?

**Comment by codekitchen** [comment]
actually shoot, watching that video again, are those `+` and `:` symbols at the beginning of each line a vi mode indicator or something? That extra character would mess up my counting of how many characters the command line is... if that's what is causing it, my whole current strategy could be in trouble.

**Comment by Aster89** [comment]
Those `+` and `:` are indeed (useful) mode indicators (insert and normal respectively).

PS: I'm on 6457a91.

**Comment by codekitchen** [comment]
Unfortunately I dug through the readline source a bit and it looks like the _true_ length of the prompt, including any mode indicator prefix, isn't exposed outside of static variables that I don't have access to.

So I'll either need to re-implement some of readline's logic to figure out what the actual prompt length is, or re-evaluate this whole approach. I'll think on it a bit.
