### ISSUE TITLE
Corrupted terminal when running a command which goes in loop

### ISSUE THREAD

**Issue by Aster89** [codekitchen/pipeline#12]
Are you able to reproduce the following? I forgot to write in the screencast the following:
- the `bash: i: command not found` error is because I just pressed <kbd>i</kbd><kbd>Enter</kbd>;
- when you see the prompt copied horizontally, that happens when I hit <kbd>Enter</kbd>.

[![asciicast](https://asciinema.org/a/Dcu8q6cUL5t4iSS323x6KUKff.svg)](https://asciinema.org/a/Dcu8q6cUL5t4iSS323x6KUKff)

**Comment by codekitchen** [comment]
hm I bet I need to trap SIGINT (and probably PIPE) and tell readline to reset some terminal state.
