### ISSUE TITLE
issues with long lines

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/pipeline#2]
There's a cheap effort to truncate long output lines so they don't wrap, but it counts bytes not characters (ya ya I know), so I'm sure it's easy to break. And there's the larger question of whether truncation is better, or should we just wrap and figure out how to still count lines properly?

There's also definitely issues with the command line being longer than one screen width, too.

**Comment by codekitchen** [comment]
This is fixed for at least the common cases, I'm sure there's still lots of lurking edge cases.

I still think maybe it should wrap long lines instead of truncating, but punting for now.

**Comment by Aster89** [comment]
I'm not sure I've understood the description of the issue. But is this the one below, or should I open a new issue?

[![asciicast](https://asciinema.org/a/b4Ak6CdZnvuSanDIgiArelyUC.svg)](https://asciinema.org/a/b4Ak6CdZnvuSanDIgiArelyUC)

**Comment by codekitchen** [comment]
New issue, this one was originally about wrapping output lines, not wrapping command line.

I'm unable to reproduce this in iTerm2 but I can reproduce in rxvt-unicode, I'm guessing it's another issue with me relying on ill-defined termcode behavior similar to what #9 was.
