### ISSUE TITLE
error in the line makes pipeline eat lines upward

### ISSUE THREAD

**Issue by Aster89** [codekitchen/pipeline#9]
I think this is closely related the first bullet point in my #7, and therefore to your #8, but it happned in d7181e2 already.

Try just entering `cat non_existent_file`. It should eat past terminal ouptut.

The following screencast shows the repro steps, but not the effect. (It must be a bug in `asciinema`!)
In my case the effect is that line goes up, "eating" the previous line of the terminal

[![asciicast](https://asciinema.org/a/hR1Kol9fk3DgqzNgBq00kh3rO.svg)](https://asciinema.org/a/hR1Kol9fk3DgqzNgBq00kh3rO)

As a side note, wouldn't be reasonable to handle <kbd>Ctrl-D</kbd> the same way you handle <kbd>Ctrl-C</kbd>? I mean, there's not much we want to do, right?

**Comment by codekitchen** [comment]
Hm this is something I've specifically tested for in the past. I just tried again with the latest master, on ubuntu+gnome terminal and macos iterm2, and I can't reproduce in either environment. So it might be some interaction with your terminal emulator (which you said was urxvt right?), or something with your terminal config. We'll have to try and narrow it down more.

**Comment by codekitchen** [comment]
Yep, I just installed rxvt-unicode on ubuntu and was able to reproduce the issue there.

**Comment by codekitchen** [comment]
I see the issue, in this situation I'm incorrectly sending the `"UP"` terminal code to move the cursor up, but with value `-1` -- these other emulators treat that negative int as `0`, but it looks like rxvt-unicode looks at the absolute value and moves up one line.

I'm not sure if one of those behaviors is "more correct" than the other, but the real solution is for pipeline to not try to move up a negative number of lines.
